services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gestion_datos_personales
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

volumes:
  pgdata:
